deployment:
  tasks:
    # Define directories to delete
    - export NESTJS_DIR=/home/kanpower/repositories/app_to_test

     # Delete .git directories if they exist
    - /bin/rm -rf $NESTJS_DIR/.git
    
    # Define deployment and build paths
    - export DEPLOYPATH=/home/kanpower/public_html
    - export BUILDPATH=dist

    # Copy build files to the deployment path
    - /bin/cp -r $BUILDPATH/* $DEPLOYPATH

    # Create or overwrite the .htaccess file in public_html for Node.js routing
    - echo "Options -Indexes" > $DEPLOYPATH/.htaccess
    - echo "RewriteEngine On" >> $DEPLOYPATH/.htaccess
    - echo "RewriteBase /" >> $DEPLOYPATH/.htaccess
    - echo "RewriteCond %{REQUEST_FILENAME} !-f" >> $DEPLOYPATH/.htaccess
    - echo "RewriteCond %{REQUEST_FILENAME} !-d" >> $DEPLOYPATH/.htaccess
    - echo "RewriteRule ^ http://127.0.0.1:3000%{REQUEST_URI} [P,L]" >> $DEPLOYPATH/.htaccess
